### ISSUE TITLE
setting up several ext directories

### ISSUE THREAD

**Issue by Remi-Gau** [joergbrech/moxunit-action#10]
Hey

Related to https://github.com/bids-standard/bids-matlab/pull/108

Trying to list several `ext` directories to add to the path of the MOxUnit github action give some weird results.

```yml
    - name: MOxUnit Action
      uses: joergbrech/moxunit-action@master
      with:
        tests: tests
        src: +bids 
        ext: JSONio tests/utils      # < ------ External resources to add to the search put (excluded from coverage)
        with_coverage: true
        cover_xml_file: coverage.xml
```

This fails: 
https://github.com/bids-standard/bids-matlab/pull/108/checks?check_run_id=1694214979

The setup phase of the action gives this (amongst other things):

```matlab
addpath(genpath("/github/workspace/JSONio tests/utils"));
```

### Expected behavior

I think I would have assumed that the set up phase would do something like this.

```matlab
addpath(genpath("/github/workspace/JSONio"));
addpath(genpath("/github/workspace/tests/utils"));
```

Am I correct in my expectations?
